name: Run Selenium Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'edge'  # default browser is Edge

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-edge
        options: --shm-size=2gb
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Run tests
        env:
          # Specify the address of the Selenium server (the container running the standalone Selenium image)
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: mvn test